-- Create site_settings table for single-value content
CREATE TABLE IF NOT EXISTS site_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create skills table
CREATE TABLE IF NOT EXISTS skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    level INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create services table
CREATE TABLE IF NOT EXISTS services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    icon_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Insert initial content for site_settings
INSERT INTO site_settings (key, value) VALUES
('hero_welcome', 'Welcome to my portfolio'),
('hero_name', 'John Doe'),
('hero_subtitle', 'A passionate web developer creating beautiful and functional digital experiences that make a difference.'),
('about_title', 'Passionate Developer & Creative Thinker'),
('about_bio_1', 'Hello! I''m a web developer with 5+ years of experience creating modern, responsive websites and applications. I love turning ideas into reality through clean code and beautiful design.'),
('about_bio_2', 'When I''m not coding, you can find me exploring new technologies, contributing to open-source projects, or enjoying a good cup of coffee.'),
('services_header_title', 'What I Offer'),
('services_header_subtitle', 'My Services'),
('services_header_description', 'I provide a wide range of services to help you achieve your digital goals.'),
('site_name', 'MyPortfolio'),
('footer_description', 'Creating beautiful digital experiences with passion and precision.')

ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- Insert initial skills
INSERT INTO skills (name, level) VALUES
('HTML/CSS', 90),
('JavaScript', 85),
('React/Next.js', 80),
('Node.js', 75)
ON CONFLICT DO NOTHING;

-- Insert initial services
INSERT INTO services (title, description, icon_name) VALUES
('Web Development', 'Building responsive, fast, and modern websites using the latest technologies like React, Next.js, and more.', 'code'),
('Mobile Responsive', 'Creating websites that look and work perfectly on all devices, from mobile phones to large desktop screens.', 'mobile'),
('UI/UX Design', 'Designing beautiful and intuitive user interfaces that provide excellent user experiences.', 'design'),
('Performance', 'Optimizing websites for speed and performance to ensure fast loading times and smooth interactions.', 'performance'),
('Clean Code', 'Writing maintainable, well-documented code that follows best practices and industry standards.', 'clean-code'),
('Support', 'Providing ongoing support and maintenance to keep your website running smoothly.', 'support')
ON CONFLICT DO NOTHING;

-- Enable RLS
ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE services ENABLE ROW LEVEL SECURITY;

-- Allow public read access (everyone can see the portfolio)
CREATE POLICY "Allow public read site_settings" ON site_settings FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read skills" ON skills FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read services" ON services FOR SELECT TO public USING (true);

-- Allow authenticated users (Admin) to manage content
CREATE POLICY "Allow admin manage site_settings" ON site_settings FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow admin manage skills" ON skills FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow admin manage services" ON services FOR ALL TO authenticated USING (true);
