-- Create projects table
CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    image_url TEXT,
    project_url TEXT,
    github_url TEXT,
    tags TEXT[], -- Array of strings for tech stack
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Add social links and image settings to site_settings
INSERT INTO site_settings (key, value) VALUES
('social_github', 'https://github.com/'),
('social_linkedin', 'https://linkedin.com/'),
('social_twitter', 'https://twitter.com/'),
('hero_image_url', '/hero-bg.png'),
('profile_image_url', '/profile.png'),
('projects_header_title', 'My Work'),
('projects_header_subtitle', 'Featured Projects'),
('projects_header_description', 'A selection of my recent work and personal projects.')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- Enable RLS for projects
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Allow public read projects" ON projects FOR SELECT TO public USING (true);

-- Allow authenticated users (Admin) to manage projects
CREATE POLICY "Allow admin manage projects" ON projects FOR ALL TO authenticated USING (true);
