-- Create the contacts table
CREATE TABLE IF NOT EXISTS contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    message TEXT NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist to avoid errors on re-run
DROP POLICY IF EXISTS "Allow public insert" ON contacts;
DROP POLICY IF EXISTS "Allow authenticated select" ON contacts;

-- Create a policy that allows ANYONE to insert (Public)
-- This uses "public" role which covers both anonymous and authenticated users
CREATE POLICY "Allow public insert" ON contacts
FOR INSERT TO public
WITH CHECK (true);

-- Create a policy that allows ANYONE to view messages (Optional)
CREATE POLICY "Allow public select" ON contacts
FOR SELECT TO public
USING (true);

/* 
  IF IT STILL FAILS: 
  You can completely disable security for this table by running:
  ALTER TABLE contacts DISABLE ROW LEVEL SECURITY;
*/

